### ISSUE TITLE
Ready for Review

### ISSUE THREAD

**Issue by bproach** [hansolbach/frontend#2]
- [x] Github-Hosted Link: https://hansolbach.github.io/frontend/INDEX.html

- [x] Frontend Repository: www.github.com/hansolbach/frontend

- [x] Backend Repository: www.github.com/hansolbach/backend
 
- [x] User Stories: https://github.com/hansolbach/frontend/blob/master/USERSTORY.txt
 
- [x] Trello: https://trello.com/b/BBaSXIwH/climate-project
 
- [x] Burndown Chart: https://docs.google.com/spreadsheets/d/1bXjECsZrEv2TN7ir8oJEM_acXrRbS3ux8sXIFs2cJGA/edit#gid=0
 
- [x] Sprint Retrospective: https://docs.google.com/document/d/1QVo63m1zKvwfIfndzjFunW9fLD02jSz28klyx6BCVMA/edit
 
- [x] Scrum Meeting Record: https://docs.google.com/document/d/1qrQcis_ZmC-DKj8Ubx1n_80nk24Pil_C1egkFQznd_Y/edit?ts=588223b6

**Comment by dmil** [comment]
@bproach - I don't have access to the "Scrum Meeting Record" - can you please allow access for me?

**Comment by dmil** [comment]
Thanks! Project has been reviewed and feedback has been sent to you via email! I'm closing this github issue.
